import React from 'react'
import Head from 'next/head'
import Assist from './assist'

function Home() {
  return (
    <React.Fragment>
      <Head>
        <title>Combined AI voice hybrid app</title>
        <meta name="description" content="Generated by nextron app for Hybrid environments" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Assist/>
    </React.Fragment>
  )
}

export default Home
